---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: ["--unsafe"] # Only check syntax, don't resolve custom tags
        exclude: |
          (?x)^(
            testdata/invalid-yaml/.*
          )$
      - id: check-json
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict

  - repo: https://github.com/trim21/dprint-pre-commit
    rev: v0.51.1.0
    hooks:
      - id: dprint
        types_or:
          - dockerfile
          - markdown
          - yaml
          - json

  - repo: local
    hooks:
      - id: golangci-lint
        name: golangci-lint
        entry: golangci-lint run --new-from-rev HEAD --fix
        language: system
        types: [go]
        require_serial: true
        pass_filenames: false

  - repo: https://github.com/hadolint/hadolint
    rev: v2.14.0
    hooks:
      - id: hadolint-docker
